### ISSUE TITLE
Integrating taiga to Perceval

### ISSUE THREAD

**Issue by valeriocos** [fioddor/taiga-client#1]
Hi @fioddor ,

First of all, thank you for working on Perceval!

If you want to develop a backend for Perceval, you should
- fork the repo https://github.com/chaoss/grimoirelab-perceval
- clone the forked repo in your machine
- have 2 remotes, one that points to your fork (`origin`) and one that points to the original repo (`upstream`)
```
$ git remote -v
origin	https://github.com/fioddor/grimoirelab-perceval (fetch)
origin	https://github.com/fioddor/grimoirelab-perceval (push)
upstream	https://github.com/chaoss/grimoirelab-perceval (fetch)
upstream	https://github.com/chaoss/grimoirelab-perceval (push)
```
- create a branch in your local repo
```
git checkout -b taiga-backend master
```
- once the work is done, you can commit and push the code to `origin`
```
git add ...
git commit ...
git push https://github.com/fioddor/grimoirelab-perceval
```
- The GitHub UI will detect the new branch and ask to create a pull request (in case you want)

Examples of this workflow are:
- a backend for the GitLab API: 
  - PR: https://github.com/chaoss/grimoirelab-perceval/pull/252
  - commit: https://github.com/valeriocos/perceval/commit/b76477b098ebf9c4e4e79a273d5964c40268251b
- a backend for the RocketChat API: 
  - PR: https://github.com/chaoss/grimoirelab-perceval/pull/661
  - origin: https://github.com/animeshk08/grimoirelab-perceval/commit/a4155deb82de1b64ed24acd7d02f73de9be2e1d4
- a backend for the Marvel API: 
  - PR: no PR since I didn't want to include this backend to Perceval
  - origin: https://github.com/valeriocos/perceval/commit/3bc21a7ffd9762e2a088a35620ce906d23db3f6f

Hope this helps,
Valerio

**Comment by fioddor** [comment]
Nice, but unfortunately it doesn't solve my problem.

My issue isn't about code integration into repository. It's about integration deployment into the grimoirelab/full container.

Taking gitlab as model, copying the relevant import sentences and even substituting the files, it doesn't import and the message doesn't provide clues. My files work together when placed in the same directory. Placing the tests up in the same path (in /dist/perceval-0.12.24 it works also. See below).  I'm overlooking something and I cannot find it.

`
/dist/perceval-0.12.24$ python3 test_minTaiga.py TestTaigaClientAgainstMockServer




Debug: Executing test_taiga as __main__ (called as ./script.py or as python3 script.py).
----------------------------------------
test_init_with_token (__main__.TestTaigaClientAgainstMockServer)
A token-born client... ... 
ok
test_init_with_user_and_pswd (__main__.TestTaigaClientAgainstMockServer)
A client is created without token. ... 
ok
test_init_without_expected_arguments_causes_exception (__main__.TestTaigaClientAgainstMockServer)
Raises exception if client is requested without expected arguments. ... 
ok
test_initialization (__main__.TestTaigaClientAgainstMockServer)
Taiga Client initializations. ... 
ok
test_login_fail (__main__.TestTaigaClientAgainstMockServer)
Taiga denies permission. ... 
ERROR:perceval.backends.core.gitlab:TaigaMinClient.login failed:
ERROR:perceval.backends.core.gitlab:TaigaMinClient.login Rq.headers : {'Accept': '*/*', 'Content-Length': '64', 'Content-Type': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.21.0', 'Connection': 'close'}
ERROR:perceval.backends.core.gitlab:TaigaMinClient.login Rq.body : bytearray(b'{ "type": "normal", "username": "a_user", "password": "a_pswd" }')
ERROR:perceval.backends.core.gitlab:TaigaMinClient.login Rs.status_code : 401
ERROR:perceval.backends.core.gitlab:TaigaMinClient.login Rs.text:
{ "etc":"etc" }
ok
test_no_permission (__main__.TestTaigaClientAgainstMockServer)
Taiga denies permission. ... 
ok
test_pj_epics (__main__.TestTaigaClientAgainstMockServer)
Taiga Project Epics. ... 
INFO:perceval.backends.core.gitlab:TaigaMinClient.rp_pages got yet 37 items out of 37.
ok
test_pj_issues_stats (__main__.TestTaigaClientAgainstMockServer)
proj_issues_stats retrieves the expected elements. ... 
ok
test_pj_stats (__main__.TestTaigaClientAgainstMockServer)
proj_stats retrieves the expected elements. ... 
ok
test_pj_tasks (__main__.TestTaigaClientAgainstMockServer)
Taiga Project Tasks. ... 
INFO:perceval.backends.core.gitlab:TaigaMinClient.rp_pages got yet 38 items out of 38.
ok
test_pj_userstories (__main__.TestTaigaClientAgainstMockServer)
Taiga Project User Stories. ... 
INFO:perceval.backends.core.gitlab:TaigaMinClient.rp_pages got yet 38 items out of 38.
ok
test_pj_wiki_pages (__main__.TestTaigaClientAgainstMockServer)
Taiga Project Wiki Pages. ... 
INFO:perceval.backends.core.gitlab:TaigaMinClient.rp_pages got yet 36 items out of 36.
ok
test_proj (__main__.TestTaigaClientAgainstMockServer)
Taiga Project data. ... 
Mock set up for https://a.taiga.instance/API/V9/projects/01
Mock set up for https://a.taiga.instance/API/V9/projects/01/stats
Mock set up for https://a.taiga.instance/API/V9/projects/01/issues_stats
Mock set up for https://a.taiga.instance/API/V9/epics?project=01
Mock set up for https://a.taiga.instance/API/V9/userstories?project=01
Mock set up for https://a.taiga.instance/API/V9/tasks?project=01
Mock set up for https://a.taiga.instance/API/V9/tasks?project=01&page=2
Mock set up for https://a.taiga.instance/API/V9/tasks?project=01&page=3
Mock set up for https://a.taiga.instance/API/V9/wiki?project=01
INFO:perceval.backends.core.gitlab:TaigaMinClient.rp_pages got yet 60 items out of 81.
INFO:perceval.backends.core.gitlab:TaigaMinClient.rp_pages got yet 81 items out of 81.
Mock set up for https://a.taiga.instance/API/V9/projects/02
Mock set up for https://a.taiga.instance/API/V9/projects/02/stats
Mock set up for https://a.taiga.instance/API/V9/projects/02/issues_stats
Mock set up for https://a.taiga.instance/API/V9/epics?project=02
Mock set up for https://a.taiga.instance/API/V9/userstories?project=02
Mock set up for https://a.taiga.instance/API/V9/userstories?project=02&page=2
Mock set up for https://a.taiga.instance/API/V9/tasks?project=02
Mock set up for https://a.taiga.instance/API/V9/wiki?project=02
INFO:perceval.backends.core.gitlab:TaigaMinClient.rp_pages got yet 38 items out of 38.
ok
test_rq_max (__main__.TestTaigaClientAgainstMockServer)
Rq stops paginating on user limit. ... 
Mock set up for https://a.taiga.instance/API/V9/tasks?project=01
Mock set up for https://a.taiga.instance/API/V9/tasks?project=01&page=2
Mock set up for https://a.taiga.instance/API/V9/tasks?project=01&page=3
INFO:perceval.backends.core.gitlab:TaigaMinClient.rp_pages got yet 60 items out of 81.
INFO:perceval.backends.core.gitlab:TaigaMinClient.rp_pages got yet 60 items out of 81.
INFO:perceval.backends.core.gitlab:TaigaMinClient.rp_pages got yet 81 items out of 81.
INFO:perceval.backends.core.gitlab:TaigaMinClient.rp_pages got yet 60 items out of 81.
INFO:perceval.backends.core.gitlab:TaigaMinClient.rp_pages got yet 81 items out of 81.
ok
test_wrong_token (__main__.TestTaigaClientAgainstMockServer)
Taiga rejects wrong token. ... 
ok

----------------------------------------------------------------------
Ran 15 tests in 0.214s

OK
`

**Comment by fioddor** [comment]
Ok. I think I've got it!

The correct deployment directory within the grimoirelab/full container isn't _/dist/perceval-0.12.24/..._, but **/usr/local/lib/python3.5/dist-packages/perceval/backends/core**.

Now test_minTaiga.py is runned ok by run_tests.py.

**Comment by valeriocos** [comment]
> The correct deployment directory within the grimoirelab/full container isn't /dist/perceval-0.12.24/..., but /usr/local/lib/python3.5/dist-packages/perceval/backends/core

You are right!

Just a minor comment about https://github.com/fioddor/taiga-client/issues/1#issuecomment-644675470,  if you develop the Perceval backend as suggested at https://github.com/fioddor/taiga-client/issues/1#issue-639513167, you can then copy the python file that includes the backend to the location /usr/local/lib/python3.5/dist-packages/perceval/backends/core in the container. This would ease the development of the backend.

Hope this helps.
